-define(EXTENSION,          ".schema").
-define(SCHEMA_MOD_PREFIX,  "hj_").
-define(SCHEMA_MOD_POSTFIX, "_schema").
-define(MOD_OPTIONS,        [export_all, return_errors, return_warnings]).
-define(DEFAULT_OUT_DIR,    "ebin").
